/**
 * Primary export.
 */

module.exports = {
  AssignmentExpression: 'AssignmentExpression',
  BlockStatement: 'BlockStatement',
  CallExpression: 'CallExpression',
  ContinueStatement: 'ContinueStatement',
  DebuggerStatement: 'DebuggerStatement',
  ReturnStatement: 'ReturnStatement',
  VariableDeclaration: 'VariableDeclaration',
  VariableDeclarator: 'VariableDeclarator',
  Program: 'Program',
  FunctionExpression: 'FunctionExpression',
  Identifier: 'Identifier',
  EmptyStatement: 'EmptyStatement',
  UnaryExpression: 'UnaryExpression',
  ThisExpression: 'ThisExpression',
  NewExpression: 'NewExpression',
  ObjectExpression: 'ObjectExpression',
  ArrayExpression: 'ArrayExpression',
  BreakStatement: 'BreakStatement',
  FunctionDeclaration: 'FunctionDeclaration',
  ExpressionStatement: 'ExpressionStatement',

  BinaryExpression: 'BinaryExpression',
  CatchClause: 'CatchClause',
  ConditionalExpression: 'ConditionalExpression',
  DoWhileStatement: 'DoWhileStatement',
  ForStatement: 'ForStatement',
  ForInStatement: 'ForInStatement',
  IfStatement: 'IfStatement',
  LabeledStatement: 'LabeledStatement',
  LogicalExpression: 'LogicalExpression',
  MemberExpression: 'MemberExpression',
  SequenceExpression: 'SequenceExpression',
  SwitchStatement: 'SwitchStatement',
  SwitchCase: 'SwitchCase',
  ThrowStatement: 'ThrowStatement',
  TryStatement: 'TryStatement',
  UpdateExpression: 'UpdateExpression',
  WhileStatement: 'WhileStatement',
  WithStatement: 'WithStatement',
};
